apiVersion: v1
kind: Secret
metadata:
  name: registrypullsecret
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson:  {{required "Need a valid entry for .Values.base64dockerconfig" .Values.base64dockerconfig }}