apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "hello-world.fullname" . }}-ui
  labels:
    app: {{ template "hello-world.fullname" . }}-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "hello-world.fullname" . }}-ui
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registryPullSecrets }}
      containers:
        - name: {{ .Chart.Name }}-ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          env:
            - name: HELLO_BACKEND_HOST
              value: {{ .Values.ui.api.host }}
            - name: HELLO_BACKEND_PORT
              value: "{{ .Values.ui.api.port }}"
          ports:
            - containerPort: {{ .Values.ui.image.internalPort }}
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: {{ .Values.ui.image.internalPort }}
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: {{ .Values.ui.image.internalPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
          resources:
            {{ toYaml .Values.resources | indent 12 }}
            {{- if .Values.nodeSelector }}
            nodeSelector:
              {{ toYaml .Values.nodeSelector | indent 8 }}
              {{- end }}